### ISSUE TITLE
Visibility of video controls on light background

### ISSUE THREAD

**Issue by Instagit** [cabin/videojs-sublime-skin#14]
Hey, just wanted to let you know about this issue we found while integrating this awesome skin into a video player:

https://github.com/Instagit/videojs-sublime/issues/10

Maybe you want to use the same solution (adding a gradient) as it really helps with light backgrounds as you can see in the screenshot.

Here's the CSS or I can prepare a pull request if you're interested.

``` CSS
/* add a gradient to the video controls */
.vjs-control-bar:before {
    content: "";
    position: absolute;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    background: -moz-linear-gradient(top, rgba(76,76,76,0) 0%, rgba(19,19,19,0.5) 100%); /* FF3.6-15 */
    background: -webkit-linear-gradient(top, rgba(76,76,76,0) 0%,rgba(19,19,19,0.5) 100%); /* Chrome10-25,Safari5.1-6 */
    background: linear-gradient(to bottom, rgba(76,76,76,0) 0%,rgba(19,19,19,0.5) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#004c4c4c', endColorstr='#80131313',GradientType=0 ); /* IE6-9 */
}
```
