### ISSUE TITLE
Support audio-only mode

### ISSUE THREAD

**Issue by zakj** [cabin/videojs-sublime-skin#15]
From Ben Mueller:

> I didn’t realize this before today, but your sublime skin doesn’t actually support audio-only mode in Video.js.  Another dev on our team had extended your CSS to include the audio-only case.  His modifications work with skin version 1, and are in fact in a production release.  
> 
> In limited testing, the modifications appear to work in 1.0.3 as well (though further testing is needed).  I figured that you might like to have the CSS we’re using so you could, if you so chose, extend the sublime skin to cover audio.  (I don’t know if this is precisely the CSS you’d want, but it should be at least a good starting point.

``` css
div.audio .vjs-sublime-skin .vjs-big-play-button {  line-height: 30px; margin: -15px; top: 50%; left: 50%; height: 30px; width: 30px; }
div.audio .vjs-sublime-skin .vjs-big-play-button:before { border-width: 15px 0 15px 30px; }

div.audio .vjs-sublime-skin.vjs-has-started .vjs-control-bar {
 display: block !important;
 visibility: visible !important;
 opacity: 1 !important;
 background-color: rgba(7, 20, 30, 1) !important;
}

div.audio .vjs-sublime-skin .vjs-progress-control { right: 55px; }
div.audio .vjs-sublime-skin .vjs-volume-control { right: 20px; }
div.audio .vjs-sublime-skin .vjs-fullscreen-control { display: none; }
```
