### ISSUE TITLE
Some buttons/controls not hidden with Video.js 4.12

### ISSUE THREAD

**Issue by Panthaaaa** [cabin/videojs-sublime-skin#6]
The following patch hides new controls/buttons in Video.js 4.12 and allows the use of a post image for the video tag:
```css
--- videojs-sublime-skin.css	2015-04-14 10:28:18.034587045 -0400
+++ new.css	2015-04-14 10:30:53.037430131 -0400
@@ -156,6 +156,8 @@
   .vjs-sublime-skin .vjs-playback-rate,
   .vjs-sublime-skin .vjs-subtitles-button,
   .vjs-sublime-skin .vjs-captions-button,
+  .vjs-sublime-skin .vjs-chapters-button,
+  .vjs-sublime-skin .vjs-caption-settings,
   .vjs-sublime-skin .vjs-mute-control {
     display: none; }
 
@@ -214,5 +216,6 @@ body.vjs-full-window {
     max-height: 100%;
     padding: 0;
     width: 100%; }
-  .video-js.vjs-using-native-controls .vjs-poster {
+  .video-js.vjs-using-native-controls .vjs-poster,
+  .vjs-sublime-skin.vjs-has-started .vjs-poster {
     display: none; }
```
