### ISSUE TITLE
Increase width of volume bar for easier access on touch devices

### ISSUE THREAD

**Issue by Panthaaaa** [cabin/videojs-sublime-skin#7]
The following patch increases the width of the volume bar for easier access on touch devices:

```css
--- videojs-sublime-skin.css	2015-04-14 10:28:18.034587045 -0400
+++ new.css	2015-04-14 10:35:43.469347716 -0400
@@ -45,7 +45,7 @@
   .vjs-sublime-skin .vjs-progress-control {
     position: absolute;
     top: 0;
-    right: 95px;
+    right: 135px;
     bottom: 0;
     left: 50px; }
     .vjs-sublime-skin .vjs-progress-control .vjs-progress-holder {
@@ -132,15 +132,15 @@
     top: 50%;
     right: 55px;
     height: 14px;
-    width: 22px; }
+    width: 60px; }
   .vjs-sublime-skin .vjs-volume-bar {
     background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAcCAQAAACw95UnAAAAMElEQVRIx2NgoBL4n4YKGUYNHkEG4zJg1OCRYDCpBowaPJwMppbLRg0eNXjUYBLEAXWNUA6QNm1lAAAAAElFTkSuQmCC);
-    background-size: 22px 14px;
+    background-size: 60px 14px;
     height: 100%;
     width: 100%; }
   .vjs-sublime-skin .vjs-volume-level {
     background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAcAQAAAAAyhWABAAAAAnRSTlMAAHaTzTgAAAAZSURBVHgBYwAB/g9EUv+JokCqiaT+U4MCAPKPS7WUUOc1AAAAAElFTkSuQmCC);
-    background-size: 22px 14px;
+    background-size: 60px 14px;
     height: 100%; }
   .vjs-sublime-skin .vjs-current-time,
   .vjs-sublime-skin .vjs-time-divider,
```
